mysite/main/urls.py
from django.urls import path
from . import views
from .views import CarListView
from .views import manage_cars

urlpatterns = [
    #path("", views.index, name="index"),
    #path("create/", views.create, name="create"),
    path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('car-list/', CarListView.as_view(), name='car-list'),
    path('manage-cars/', manage_cars, name='manage-cars'),
    path('send-promotion/', views.send_promotion_email, name='send_promotion'),

]

mysite/mysite/urls.py

from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("main.urls")),
    path('', include("main.urls")),
    path("register/", v.register, name="register"),
    path('', include("django.contrib.auth.urls")),
    path('bookings/', include('bookings.urls')),
]

mysite/bookings/models.py
from django.db import models
from main.models import Car 
from django.contrib.auth.models import User


class Booking(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    start_date = models.DateField()
    end_date = models.DateField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)    

    def __str__(self):
        return f"Booking for {self.car} by {self.user}"

mysite/main/models.py
from django.db import models
from django.contrib.auth.models import User
from . import pricing_states
from .decorators import PricingDecorator, InsuranceDecorator


# Create your models here.
class Car(models.Model):
    COLOUR_CHOICES = (
    ('Black', 'Black'),
    ('Blue', 'Blue'),
    ('Brown', 'Brown'),
    ('Gray', 'Gray'),
    ('Green', 'Green'),
    ('LightBlue', 'LightBlue'),
    ('Navy', 'Navy'),
    ('Red', 'Red'),
    ('Silver', 'Silver'),
    ('White', 'White'),
    )

    YEAR_CHOICES = (
        (2023, '2023'),
        (2022, '2022'),
        (2021, '2021'),
        (2020, '2020'),
        (2019, '2019'),
        (2018, '2018'),
        (2017, '2017'),
        (2016, '2016'),
        (2015, '2015'),
    )

    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    colour = models.CharField(max_length=20, choices=COLOUR_CHOICES)
    year = models.IntegerField(choices=YEAR_CHOICES)
    price_per_day = models.DecimalField(max_digits=10, decimal_places=2)
    is_available = models.BooleanField(default=True)
    pricing_state = models.CharField(max_length=20, default='RegularPricingState') 

    def calculate_rental_price(self, car_price):
        # Instantiate the current pricing state and calculate the price
        current_state = getattr(pricing_states, self.pricing_state)()
        rental_price = current_state.calculate_price(car_price)
        decorated_car = InsuranceDecorator(self)
        return decorated_car.calculate_price(rental_price)

# sedan inherits from car model and has additional field
class Sedan(Car):
    trunk_capacity = models.IntegerField()
    pass

# coupe inherits from car model and has additional field
class Coupe(Car):
    has_panoramic_roof = models.BooleanField(default=False)
    pass

mysite/main/forms.py
from django import forms
from .models import Car

#form to be displayed on list page and filter page
class CarFilterForm(forms.Form):
    car_make = forms.ChoiceField(
        choices=[('', 'All Car Types')] + list(Car.objects.values_list('make', 'make').distinct()),
        required=False
    )
    car_year = forms.ChoiceField(
        choices=[('', 'All Car Years')] + list(Car.objects.values_list('year', 'year').distinct()),
        required=False
    )
    car_colour = forms.ChoiceField(
        choices=[('', 'All Car Colors')] + list(Car.objects.values_list('colour', 'colour').distinct()),
        required=False
    )
    max_price = forms.DecimalField(min_value=0, required=False)
    #start_date = forms.DateField(required=False, widget=forms.SelectDateWidget(years=range(2023, 2030)))
    #end_date = forms.DateField(required=False, widget=forms.SelectDateWidget(years=range(2023, 2030)))

mysite/main/views.py
from urllib.parse import urlencode
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from .forms import CarFilterForm
from .models import Car, Sedan, Coupe
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import datetime
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from .factories import SedanFactory, CoupeFactory
from observer.subject import PromotionService
from django.http import HttpResponseRedirect
from django.urls import reverse
from observer.observers import EmailAlertObserver


# Create your views here.

def index(response):
    return render(response, "main/base.html", {})

def home(response):
    return render(response, "main/home.html", {})



@staff_member_required
def send_promotion_email(request):
    if request.method == 'POST':
        # Gets all users who are not staff and have an email address
        users = User.objects.filter(is_staff=False).exclude(email='')

        # Creates a PromotionService instance and attaches observers for each users email
        promotion_service = PromotionService()
        for user in users:  
            observer = EmailAlertObserver(user.email)
            promotion_service.attach(observer)

        # sends the message to observers
        promotion_service.notify('Going somewhere this christmas? Book a car with us!')

        # Redirect back to the homepage with a success message
        return HttpResponseRedirect(reverse('home'))
    

class CarListView(ListView):
    model = Car
    template_name = 'main/car_list.html'  # Create this template next
    context_object_name = 'cars'
    object_list = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CarFilterForm(self.request.GET)
        return context
    
    def get(self, request, *args, **kwargs):
        #get filters from the URL
        car_make = request.GET.get('car_make')
        car_year = request.GET.get('car_year')
        car_colour = request.GET.get('car_colour')
        max_price = request.GET.get('max_price')

        #Start with a list of all cars
        cars = Car.objects.all()

        #Apply filters to our cars list
        if car_make:
            cars = cars.filter(make=car_make)
        if car_year:
            cars = cars.filter(year=car_year)
        if car_colour:
            cars = cars.filter(colour=car_colour)
        if max_price is not None:
            cars = cars.filter(price_per_day__lte=max_price)
        
        #self.object_list = cars

        #place our now filtered list into our context object to be sent to the template
        custom_context = {
            'filtered_cars': cars,
        }

        context = self.get_context_data()
        context.update(custom_context)

        return render(request, self.template_name, context)


    def post(self, request, *args, **kwargs):
        form = CarFilterForm(request.POST)
        cars = Car.objects.all()  # Start with all cars
        if form.is_valid():
            
            #take filter results which the user has given
            car_make = form.cleaned_data.get('car_make')
            car_year = form.cleaned_data.get('car_year')
            car_colour = form.cleaned_data.get('car_colour')
            max_price = form.cleaned_data.get('max_price')

            #Start with a list of all cars
            cars = Car.objects.all()

            #Apply filters to our cars
            if car_make:
                cars = cars.filter(make=car_make)
            if car_year:
                cars = cars.filter(year=car_year)
            if car_colour:
                cars = cars.filter(colour=car_colour)
            if max_price is not None:
                cars = cars.filter(price_per_day__lte=max_price)

            #Store the selected filters in our url
            url_params = {}
            if car_make:
                url_params['car_make'] = car_make
            if car_year:
                url_params['car_year'] = car_year
            if car_colour:
                url_params['car_colour'] = car_colour
            if max_price is not None:
                url_params['max_price'] = max_price

            # Redirect to the URL with the updated query parameters
            return redirect(f'{self.request.path_info}?{urlencode(url_params)}')

        #self.object_list = cars

        custom_context = {
            'filtered_cars': cars,
        }

        context = self.get_context_data()
        context.update(custom_context)

        return render(request, self.template_name, context)


def update_pricing():
    cars = Car.objects.all()

    current_date = datetime.date.today()

    # Update pricing state for each car based on conditions
    for car in cars:

        # Set pricing state based on conditions
        if current_date.weekday() in [5, 6]:  # 5 and 6 correspond to Saturday and Sunday
            car.pricing_state = 'WeekendPricingState'
        #elif current_date == event:
            #car.pricing_state = 'PromotionPricingState'
        else:
            car.pricing_state = 'RegularPricingState'

        car.save()


@staff_member_required
def manage_cars(request):
    # Creating instances of the Factories
    sedan_factory = SedanFactory()
    coupe_factory = CoupeFactory()

    # Creating an instance of sedan/coupe using the factories
    sedan = sedan_factory.create_car()
    coupe = coupe_factory.create_car()

    # fetching the list of all cars
    cars = Car.objects.all()

    # making it so cars can be deleted and removed from database
    if request.method == 'POST':
        car_id = request.POST.get('car_id')
        if car_id:
            car = get_object_or_404(Car, id=car_id)
            car.delete()
            return redirect('manage-cars')

    # Renders the page for manage cars, that displays the details of sedans and coupes
    return render(request, 'main/manage_cars.html', {'sedan': sedan, 'coupe': coupe, 'cars': cars})

 





mysite/main/templates/main/base.html
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <style type="text/css">
        body {
            font-family: 'Open Sans', sans-serif; 
        }

        h1 {
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #054274;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .sidenav a {
            padding: 6px 8px 6px 18px;
            text-decoration: none;
            color: #a7d7ff;
            font-size: 25px;
            display: block;
        }

        .sidenav a:hover {
            padding: 6px 8px 6px 18px;
            text-decoration: none;
            color: #f1f1f1;
            font-size: 25px;
            display: block;
        }

        .main {
            margin-left: 270px;
            padding: 0px 10px;
        }
    </style>

    <title>{% block title %}Home{% endblock %}</title>
</head>
<body> 
    


{% if user.is_authenticated %}
    <div class="sidenav">
        <a href="/home">Home</a>
        <a href="/car-list">Car List</a>

            <a href="{% url 'view-bookings' %}">Your Bookings</a>
        {% if user.is_staff %}
            
            <a href="{% url 'view-all-bookings' %}">Manage Bookings</a>
            <a href="{% url 'manage-cars' %}">Manage Cars</a>
            <a href="{% url 'admin:index' %}">Admin Panel</a>
        {% endif %}
        <a href="/logout">Log out</a>
    </div>
{% endif %}


    <div id="content" name="content" class="main">

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/main/templates/main/car_list.html
{% extends 'main/base.html' %}

{% block content %}
<div style="width: 90%;">
  <h1>Car List</h1>

  <form method="post" action="{% url 'car-list' %}">
    {% csrf_token %}
    <label for="{{ form.car_make.id_for_label }}">Car Make:</label>
    {{ form.car_make }}
    
    <label for="{{ form.car_year.id_for_label }}">Car Year:</label>
    {{ form.car_year }}
    
    <label for="{{ form.car_colour.id_for_label }}">Car Colour:</label>
    {{ form.car_colour }}
    
    <label for="{{ form.max_price.id_for_label }}">Max Price:</label>
    {{ form.max_price }}
    
    <button type="submit" class="btn btn-primary">Apply Filters</button>
  </form>

  <table style="width: 800px;" class="table table-bordered">
    <thead>
      <tr>
        <th>Car</th>
        <th>Colour</th>
        <th>Price per day</th>
        <th>Available</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for car in filtered_cars %}
        <tr>
          <td>{{ car.make }} {{ car.model }} ({{ car.year }})</td>
          <td>{{ car.colour }}</td>
          <td>${{ car.price_per_day }}</td>
          <td>
            {% if car.booking_set.all %}
              No
            {% else %}
              Yes
            {% endif %}
          </td>
          <td>
            {% if car.is_available and not car.booking_set.all %}
              <a href="{% url 'book-car' car.id %}" class="btn btn-success">Book Now</a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

mysite/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Home Page</h1>

    {% if not user.is_authenticated %}
        <div class="centered-div">
            <a class="login-button" href="/login">Login</a>
            <a class="register-button" href="/register">Register</a>
        </div>
    {% else %}
        <p>Welcome, {{ user.username }}!</p>
    
        {% if user.is_staff %}
        <form action="{% url 'send_promotion' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Send Promotion Email</button>
        </form>
        {% endif %}

        <p>View our cars: <a href="{% url 'car-list' %}">Car List</a></p>
    {% endif %}
{% endblock %}

mysite/main/templates/main/manage_booking.html
{% extends 'main/base.html' %}

{% block title %}Manage Booking{% endblock %}

{% block content %}
  <h1>Manage Booking</h1>

  <p>Car: {{ booking.car.make }} {{ booking.car.model }} ({{ booking.car.year }})</p>
  <p>Colour: {{ booking.car.colour }}</p>
  <p>{{ info }}</p>
  <p>Price per day: {{ price_per_day }}</p>
  <p>Booking days: {{ booking.booking_days }}</p>
  <p>Total Price: {{ total_price }}</p>

  <a href="{% url 'process-payments' booking_id=booking.id %}">Pay Now</a>

  
{% endblock %}

mysite/main/templates/main/manage_cars.html
{% extends 'main/base.html' %}

{% block content %}

<html>
<head>
    <title>Manage Cars</title>
    <style>
        h1 {
            color: #333;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .delete-button {
            background-color: #ff6666;
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <h1>Manage Cars</h1>

    <p>Sedan Details:</p>
    <ul>
        <li>Trunk Capacity: {{ sedan.trunk_capacity }}</li>
    </ul>

    <p>Coupe Details:</p>
    <ul>
        <li>Panoramic Roof: {% if coupe.has_panoramic_roof %}Yes{% else %}No{% endif %}</li>
    </ul>

    <p>All Cars:</p>
    <table>
        <tr>
            <th>Make</th>
            <th>Model</th>
            <th>Year</th>
            <th>Action</th>
        </tr>
        {% for car in cars %}
            <tr>
                <td>{{ car.make }}</td>
                <td>{{ car.model }}</td>
                <td>{{ car.year }}</td>
                <td>
                    <form method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="car_id" value="{{ car.id }}">
                        <button class="delete-button" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

{% endblock %}

mysite/main/templates/main/payment_successful.html
{% extends 'main/base.html' %}

{% block title %}Payment Successful{% endblock %}

{% block content %}
  <h1>Payment Successful</h1>
  <p>Your payment was successful!</p>
  <a href="{% url 'home' %}">Return to Home Page</a>
{% endblock %}

mysite/main/templates/main/process_payments.html
{% extends 'main/base.html' %}

{% block title %}Process Payment{% endblock %}

{% block content %}

  <h1>Process Payment</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Pay Now</button>
  </form>
{% endblock %}

mysite/main/templates/main/profile.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Profile</h1>

    {% if not user.is_authenticated %}
        <script type="text/javascript">
            window.location.href = "/register";
        </script>
    {% else %}

    <style>
        h2 {
            color: rgb(109, 109, 255);
        }
    </style>

        <h2>User Information</h2>
        <p><strong>Username:</strong> {{ user.username }} <a href="">Edit</a></p>
        <p><strong>Email:</strong> {{ user.email }} <a href="">Edit</a></p>
        <p><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }} <a href="">Edit</a></p>

        <p><strong>License Number:</strong> {{ user.licensenumber }} <a href="">Edit</a></p>
        <br>
        <p><a href="">Edit Payment Info</a></p>

        <br><br>
        <h2>Upcoming Bookings</h2>

        <br><br>
        <h2>Past Bookings</h2>

    {% endif %}
{% endblock %}

mysite/main/templates/main/redirect.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Profile</h1>

    {% if not user.is_authenticated %}
    <script type="text/javascript">
        window.location.href = "/register";
    </script>

    {% else %}
        <p>
            Currently logged in as {{ user.username }}.
            <br>
            <br>
            Below you can view your information along with update it

        </p>
        
    

    
    {% endif %}
{% endblock %}